version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test123!
      MYSQL_DATABASE: books
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

  backend1:
    build: .
    container_name: fastapi-backend-1
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  backend2:
    build: .
    container_name: fastapi-backend-2
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - backend1
      - backend2

volumes:
  db_data:
